/**
 * Incarnations — seed initial.
 *
 * 17 motifs YPM + 13 incarnations transposés depuis
 * apps/atelier-incarnation/migration_incarnations.sql.
 */

import type { Incarnation, Motif } from "@/types/incarnations";

export const SEED_MOTIFS: Motif[] = [
  { code: "YPM-001", nom: "La Brigitte", famille: "Cœurs" },
  { code: "YPM-002", nom: "L'Ambre", famille: "Cœurs" },
  { code: "YPM-003", nom: "Le Club", famille: "Signes/Badges" },
  { code: "YPM-004", nom: "Notre Héritage", famille: "Liens familiaux" },
  { code: "YPM-005", nom: "L'Annonce", famille: "Mariage/EVJF" },
  { code: "YPM-006", nom: "Le Câlin", famille: "Cœurs" },
  { code: "YPM-007", nom: "Le Chouchou", famille: "Scripts" },
  { code: "YPM-008", nom: "La Féline", famille: "Cœurs" },
  { code: "YPM-009", nom: "La Palette", famille: "Famille" },
  { code: "YPM-010", nom: "La Ronde", famille: "Aa Typo" },
  { code: "YPM-011", nom: "La Confidence", famille: "Cœurs" },
  { code: "YPM-012", nom: "La Meute", famille: "Aa Typo" },
  { code: "YPM-013", nom: "Le Depuis", famille: "Scripts" },
  { code: "YPM-014", nom: "La Tigresse", famille: "Cœurs" },
  { code: "YPM-015", nom: "La Déclaration", famille: "Cœurs" },
  { code: "YPM-016", nom: "La Signature", famille: "Scripts" },
  { code: "YPM-017", nom: "La Florale", famille: "Aa Typo" },
];

const ts = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
};

interface IncarnationSeed
  extends Omit<Incarnation, "id" | "created_at" | "updated_at"> {
  uploaded_days_ago: number;
}

const SEEDS: IncarnationSeed[] = [
  {
    code: "YPI-001",
    nom_commercial: "MAMA CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "MAMA",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Vert sapin",
    },
    gabarits_cibles: ["YP001", "YP005", "YP019"],
    collections_cibles: ["pour-maman", "fete-des-meres", "naissance"],
    ton: "tendre",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 30,
  },
  {
    code: "YPI-002",
    nom_commercial: "PAPA CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "PAPA",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Bleu marine",
    },
    gabarits_cibles: ["YP001", "YP019"],
    collections_cibles: ["pour-papa", "fete-des-peres"],
    ton: "tendre",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 30,
  },
  {
    code: "YPI-003",
    nom_commercial: "SISTA CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "SISTA",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Rose framboise",
    },
    gabarits_cibles: ["YP001", "YP005"],
    collections_cibles: ["pour-soeur", "pour-amie", "anniversaire"],
    ton: "complice",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 28,
  },
  {
    code: "YPI-004",
    nom_commercial: "FAMILLE CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "FAMILLE",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Bleu marine",
    },
    gabarits_cibles: ["YP001", "YP019"],
    collections_cibles: ["pour-famille", "noel"],
    ton: "tendre",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 28,
  },
  {
    code: "YPI-005",
    nom_commercial: "AMOUR CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "AMOUR",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Rose framboise",
    },
    gabarits_cibles: ["YP005"],
    collections_cibles: ["pour-couple", "saint-valentin"],
    ton: "tendre",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 25,
  },
  {
    code: "YPI-006",
    nom_commercial: "BRIDE TEAM",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "BRIDE",
      mot_bas: "TEAM",
      symbole: "Cœur",
      couleur_fil_defaut: "Rose poudré",
    },
    gabarits_cibles: ["YP001"],
    collections_cibles: ["pour-mariee", "evjf", "mariage"],
    ton: "complice",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 25,
  },
  {
    code: "YPI-007",
    nom_commercial: "DOG DAD GANG",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "DOG DAD",
      mot_bas: "GANG",
      symbole: "Patte",
      couleur_fil_defaut: "Crème",
    },
    gabarits_cibles: ["YP001"],
    collections_cibles: ["pour-papa", "animaux"],
    ton: "complice",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 20,
  },
  {
    code: "YPI-008",
    nom_commercial: "CREW SUMMER",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "CREW",
      mot_bas: "SUMMER",
      symbole: "Fleur",
      couleur_fil_defaut: "Bleu marine",
    },
    gabarits_cibles: ["YP001"],
    collections_cibles: ["pour-amies", "ete", "voyage"],
    ton: "complice",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 20,
  },
  {
    code: "YPI-009",
    nom_commercial: "TEAM DOG",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "TEAM",
      mot_bas: "DOG",
      symbole: "Patte",
      couleur_fil_defaut: "Crème",
    },
    gabarits_cibles: ["YP001"],
    collections_cibles: ["pour-famille", "animaux"],
    ton: "complice",
    statut: "actif",
    notes: null,
    uploaded_days_ago: 20,
  },
  {
    code: "YPI-010",
    nom_commercial: "PAPI CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "PAPI",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Bleu marine",
    },
    gabarits_cibles: ["YP001", "YP005", "YP019"],
    collections_cibles: ["pour-papi", "grands-parents", "fete-des-peres"],
    ton: "tendre",
    statut: "a_shooter",
    notes: null,
    uploaded_days_ago: 12,
  },
  {
    code: "YPI-011",
    nom_commercial: "MAMIE CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "MAMIE",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Vert sauge",
    },
    gabarits_cibles: ["YP001", "YP005", "YP019"],
    collections_cibles: ["pour-mamie", "grands-parents", "fete-des-meres"],
    ton: "tendre",
    statut: "a_shooter",
    notes: null,
    uploaded_days_ago: 12,
  },
  {
    code: "YPI-012",
    nom_commercial: "CONNASSE CLUB",
    motif_ypm: "YPM-003",
    spec_broderie: {
      mot_haut: "CONNASSE",
      mot_bas: "CLUB",
      symbole: "Cœur",
      couleur_fil_defaut: "Bordeaux",
    },
    gabarits_cibles: ["YP001", "YP005", "YP019"],
    collections_cibles: ["pour-bff", "evjf", "humour"],
    ton: "humour",
    statut: "concept",
    notes: null,
    uploaded_days_ago: 6,
  },
  {
    code: "YPI-013",
    nom_commercial: "COOL GIRLS",
    motif_ypm: "YPM-016",
    spec_broderie: {
      mot_haut: "Cool",
      mot_bas: "Girls",
      symbole: "—",
      couleur_fil_defaut: "Rose framboise",
    },
    gabarits_cibles: ["YP001", "YP005", "YP019"],
    collections_cibles: ["pour-amies", "anniversaire", "ete"],
    ton: "complice",
    statut: "concept",
    notes: null,
    uploaded_days_ago: 3,
  },
];

export const SEED_INCARNATIONS: Incarnation[] = SEEDS.map((s) => ({
  id: `seed-${s.code}`,
  code: s.code,
  nom_commercial: s.nom_commercial,
  motif_ypm: s.motif_ypm,
  spec_broderie: s.spec_broderie,
  gabarits_cibles: s.gabarits_cibles,
  collections_cibles: s.collections_cibles,
  ton: s.ton,
  statut: s.statut,
  description_template: null,
  notes: s.notes,
  created_at: ts(s.uploaded_days_ago),
  updated_at: ts(s.uploaded_days_ago),
}));
